// For JetBrains IDE: HTTP requests to test API

### GET about
GET http://localhost:8000

### GET cases
GET http://localhost:8000/cases

###
### GET states
GET http://localhost:8000/states

###
###
### GET commissions
GET http://localhost:8000/commissions/11350000

###